//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.ObjectModel;
    using System.ComponentModel.DataAnnotations;

    [Serializable]public partial class bar_to_weak
    {
        public int barcode { get; set; }
        public int weakcode { get; set; }
        public Nullable<double> value { get; set; }
        public int id { get; set; }
    
        public virtual barrier barrier { get; set; }
        public virtual weakness weakness { get; set; }
    }
}
