//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.ObjectModel;
    
    [Serializable]public partial class def_to_objtype
    {
        public int code { get; set; }
        public Nullable<int> defcode { get; set; }
        public Nullable<int> paramcode { get; set; }
        public Nullable<int> paramtype { get; set; }
    
        public virtual defenseobj defenseobj { get; set; }
    }
}
