//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.ObjectModel;
    
    [Serializable]public partial class defenseobj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public defenseobj()
        {
            this.def_to_objtype = new ObservableCollection<def_to_objtype>();
        }
    
        public int defcode { get; set; }
        public string name { get; set; }
        public Nullable<int> deftype_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<def_to_objtype> def_to_objtype { get; set; }
        public virtual defenseobj_types defenseobj_types { get; set; }
    }
}
