//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.ObjectModel;
    
    [Serializable]public partial class prot_to_obj
    {
        public int objcode { get; set; }
        public int protcode { get; set; }
        public Nullable<double> value { get; set; }
        public int id { get; set; }
    
        public virtual @object @object { get; set; }
        public virtual protect_mech protect_mech { get; set; }
    }
}
