//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.ObjectModel;
    
    [Serializable]public partial class warnings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public warnings()
        {
            this.war_to_prot = new ObservableCollection<war_to_prot>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> damage_cost { get; set; }
        public string description { get; set; }
        public Nullable<int> warning_type { get; set; }
        public Nullable<int> danger_class { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<war_to_prot> war_to_prot { get; set; }
    }
}
